ip_proxy/app/urls.py
from django.conf.urls import url


from app import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^left/', views.left, name='left'),
    url(r'^head/', views.head, name='head'),
    url(r'^ip_list/(\d+)/$', views.ip_list, name='ip_list'),
    url(r'^search/', views.ip_search, name='ip_search'),
    url(r'^detial/', views.detial, name='detial')
]

ip_proxy/ip_proxy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app'))
]

ip_proxy/app/models.py
import pyssdb


class SsdbModel(object):

    def __init__(self):
        self.host = '10.28.100.151'
        self.port = 8888
        # self.client = pyssdb.Client(host=self.host, port=self.port)
        # self.client = pyssdb.ConnectionPool(host=self.host, port=self.port)
        self.client = ''
    def get_fast_proxy(self):
        """
        获取代理延迟小于300ms的代理
        :return:
        """
        return self.client.keys('0_', '0_~', 10000)

    def get_yun_proxy(self):
        """
        获取代理云
        :return:
        """
        return self.client.keys('1_', '1_~', 10000)

    def get_owner_proxy(self):
        """
        获取自建代理
        :return:
        """
        return self.client.keys('2_', '2_~', 10000)

    def get_other_proxy(self):
        """
        获取其他代理
        :return:
        """
        return self.client.keys('3_', '3_~', 10000)

    def get_back_proxy(self):
        """
        获取黑名单
        :return:
        """
        return self.client.keys('b_', 'b_~', 1000000)

    def get_ttl(self, ip):
        return str(self.client.ttl(ip))[2:-1]

    def get_ip(self, msg):
        return self.client.keys('msg', 'msg~', 1000000)

    def to_dict(self, base):
        base_ip = str(base)[2:-2]
        port = base_ip.split(':')[1]
        ip = base_ip.split(':')[0].split('_')[1]
        return {
            'ip': ip,
            'port': port,
        }

ip_proxy/app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from app.models import SsdbModel

ssdb_model = SsdbModel()

def ip_list(request, ip_type):
    if ip_type == '0':
        list_ip = ssdb_model.get_fast_proxy()
    if ip_type == '1':
        list_ip = ssdb_model.get_yun_proxy()
    if ip_type == '2':
        list_ip = ssdb_model.get_owner_proxy()
    if ip_type == '3':
        list_ip = ssdb_model.get_other_proxy()
    page_num = request.GET.get('page_num', 1)
    ttl_list = list(map(ssdb_model.get_ttl, list_ip[(int(page_num) - 1) * 20: int(page_num) * 20]))
    ip_info = [ssdb_model.to_dict(ip) for ip in list_ip]
    for i in range(20):
        ip_info[(int(page_num) - 1) * 20 + i]['ttl'] = ttl_list[i]
    paginator = Paginator(ip_info, 20)
    pages = paginator.page(int(page_num))
    ctx = {
        'ip_type': ip_type,
        'pages': pages,
    }
    return render(request, 'ip_list.html', ctx)


def ip_search(request):
    ip = request.GET.get('ip')
    ip_types = ['0_1_', '0_2_', '0_3_', '1_', '2_', '3_', 'b_']
    list_ip = []
    for ip_type in ip_types:
        ip_info = ip_type + ip
        if ssdb_model.get_ip(ip_info):
            list_ip.extend(ssdb_model.get_ip(ip_info))
    page_num = request.GET.get('page_num', 1)
    ttl_list = list(map(ssdb_model.get_ttl, list_ip[(int(page_num) - 1) * 20: int(page_num) * 20]))
    ip_info = [ssdb_model.to_dict(ip) for ip in list_ip]
    for i in range(20):
        ip_info[(int(page_num) - 1) * 20 + i]['ttl'] = ttl_list[i]
    paginator = Paginator(ip_info, 20)
    pages = paginator.page(int(page_num))
    ctx = {
        'pages': pages,
    }
    return render(request, 'search.html', ctx)


def index(request):

    return render(request, 'index.html')


def left(request):
    return render(request, 'left.html')


def head(request):
    return render(request, 'head.html')


def detial(request):

    return render(request, 'detial.html')

ip_proxy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extcss %}
    {% endblock %}
    {% block extjs %}
        <script src="/static/js/jquery-1.10.1.min.js"></script>
    {% endblock %}

    </head>
    {% block indexbody %}
    {% endblock %}
    <body>
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
    </body>
    {% block extsctipt %}
    {% endblock %}
    </html>

ip_proxy/templates/detial.html
{% extends 'base.html' %}
{% block extcss %}
<style>
table{
    height:230px;
    width:800px;
    border: 1px solid;
}
    td {
        border: solid 1px;
        text-align: center;
    }
    th{
        border:1px solid;
        text-align: center;
    }
</style>

{% endblock %}
{% block content %}
    <table cellspacing="0">
        <tr>
            <td colspan="4">可用ip</td>
            <td>黑名单</td>
        </tr>
        <tr>
            <td>fast</td>
            <td>代理云</td>
            <td>自建代理</td>
            <td>其它代理</td>
            <td rowspan="2">100000</td>

        </tr>
        <tr>
            <td>100</td>
            <td>200</td>
            <td>300</td>
            <td>400</td>
        </tr>
        <tr>
          <td colspan="4">可用ip共</td>
            <td>合计ip: 1000000</td>
        </tr>
    </table>
{% endblock %}
{% block extjs %}
{% endblock %}

ip_proxy/templates/head.html
{% extends 'base.html' %}
{% block extcss %}
    <style>
        form{
            position: absolute;
            right: 100px;
            bottom: 15px;
        }
    </style>
{% endblock %}
{% block content %}
    <form action="{% url 'app:ip_search' %}">
        <input type="text" name="ip">
        <submit><button>搜索</button></submit>
    </form>
{% endblock %}
{% block extjs %}
{% endblock %}

ip_proxy/templates/index.html
{% extends 'base.html' %}
    {% block title %}
        首页{{ user.username }}
    {% endblock %}
    {% block indexbody %}
        <frameset rows="50,*" cols="*" scrolling="No" framespacing="0"
            frameborder="no" border="0"> <frame src="{% url 'app:head' %}"
            name="headmenu" id="mainFrame" title="mainFrame"><!-- 引用头部 -->
        <!-- 引用左边和主体部分 --> <frameset rows="100*" cols="220,*" scrolling="No"
            framespacing="0" frameborder="no" border="0"> <frame
            src="{% url 'app:left' %}" name="leftmenu" id="mainFrame" title="mainFrame">
        <frame src="{% url 'app:ip_list' 0 %}" name="main" scrolling="yes" noresize="noresize"
            id="rightFrame" title="rightFrame"></frameset></frameset>
    {% endblock %}

ip_proxy/templates/ip_list.html
{% extends 'base.html' %}
{% block extcss %}
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
{% endblock %}
{% block content %}
<div id="MainForm">
<div class="form_boxA">
<table cellpadding="0" cellspacing="0">
    <tr>
        <th>ORDER</th>
        <th>IP</th>
        <th>PORT</th>
        <th>TTL</th>
    </tr>
    {% for ip_info in pages %}
    {% with num=forloop.counter0 %}
    <tr>
        <td></td>
        <td>{{ ip_info.ip }}</td>
        <td>{{ ip_info.port }}</td>
        <td>{{ ip_info.ttl }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
</table>
<p class="msg">共找到{{ pages.paginator.count }}条年度预算记录，当前显示从第{{ pages.start_index }}条至第{{ pages.end_index }}条</p>
</div>

<ul id="PageNum">
    {% if pages.has_previous %}
    <li>
        <a href="{% url 'app:ip_list' ip_type %}?page_num={{ pages.previous_page_number }}">上一页</a>
    </li>
    {% endif %}
    {% for page in pages.paginator.page_range %}
        <li><a href="{% url 'app:ip_list' ip_type %}?page_num={{ page }}">{{ page }}</a></li>
    {% endfor %}
    {% if pages.has_next %}
    <li>
        <a href="{% url 'app:ip_list' ip_type %}?page_num={{ pages.next_page_number }}">下一页</a>
    </li>
    {% endif %}
    <li id="page_num" value="{{ pages.number }}">当前第{{ pages.number }}页</li>

    <li><a href="{% url 'app:ip_list' ip_type %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
</ul>

</div>
{% endblock %}
{% block extjs %}
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>
{% endblock %}

ip_proxy/templates/left.html
{% extends 'base.html' %}
{% block title %}
首页左侧导航
{% endblock %}
{% block extcss %}
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
{% endblock %}


{% block content %}
	<!-- 左边节点 -->
	<div class="container">
		<div class="leftsidebar_box">
			<dl class="system_log">
				<dt>
					活跃IP<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>

				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:ip_list' '0' %}"
						target="main">Fast</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>

				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:ip_list' '1' %}"
						target="main">代理云</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:ip_list' '2' %}"
						target="main">自建代理</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks" href="{% url 'app:ip_list' '3' %}"
						target="main">其它代理</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>

			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coin03.png" />黑名单<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
			</dl>
			<dl class="system_log">
				<dt>
					<a class="cks" href="{% url 'app:detial' %}"
						target="main"><img class="icon1" src="/static/img/coinL1.png" />综合查询<img class="icon3"
						src="/static/img/coin19.png" /></a>
				</dt>

			</dl>

		</div>

	</div>

{% endblock %}
{% block extjs %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="/static/js/public.js"></script>
{% endblock %}

ip_proxy/templates/search.html
{% extends 'base.html' %}
{% block extcss %}
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
{% endblock %}
{% block content %}
<div id="MainForm">
<div class="form_boxA">
<table cellpadding="0" cellspacing="0">
    <tr>
        <th>ORDER</th>
        <th>IP</th>
        <th>PORT</th>
        <th>TTL</th>
    </tr>
    {% for ip_info in pages %}
    <tr>
        <td></td>
        <td>{{ ip_info.ip }}</td>
        <td>{{ ip_info.port }}</td>
        <td>{{ ip_info.ttl }}</td>
    </tr>
    {% endfor %}
</table>
<p class="msg">共找到{{ pages.paginator.count }}条年度预算记录，当前显示从第{{ pages.start_index }}条至第{{ pages.end_index }}条</p>
</div>

<ul id="PageNum">
    {% if pages.has_previous %}
    <li>
        <a href="{% url 'app:ip_search'%}?page_num={{ pages.previous_page_number }}">上一页</a>
    </li>
    {% endif %}
    {% for page in pages.paginator.page_range %}
        <li><a href="{% url 'app:ip_search'  %}?page_num={{ page }}">{{ page }}</a></li>
    {% endfor %}
    {% if pages.has_next %}
    <li>
        <a href="{% url 'app:ip_search' %}?page_num={{ pages.next_page_number }}">下一页</a>
    </li>
    {% endif %}
    <li id="page_num" value="{{ pages.number }}">当前第{{ pages.number }}页</li>

    <li><a href="{% url 'app:ip_search'  %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
</ul>

</div>
{% endblock %}
{% block extjs %}
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>
{% endblock %}